# Generated by Django 5.2.7 on 2025-10-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_consumable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consumables/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='modification',
            field=models.CharField(max_length=10, verbose_name='Модификация'),
        ),
    ]
