# Generated by Django 5.2.7 on 2025-11-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_consumable_image_alter_consumable_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='model',
            field=models.CharField(default=1, max_length=100, verbose_name='Модель'),
            preserve_default=False,
        ),
    ]
