# Generated by Django 5.2.7 on 2025-11-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('issued', 'Выдано')], default='pending', max_length=20),
        ),
    ]
