# Generated by Django 5.2.7 on 2025-11-14 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_request_options_alter_request_issued_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдан')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable', verbose_name='Расходник')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_made', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получил')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдачи',
                'ordering': ['-issued_at'],
            },
        ),
    ]
