# Generated by Django 5.2.7 on 2025-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='modification',
            field=models.CharField(blank=True, max_length=10, verbose_name='Модификация'),
        ),
    ]
