# Generated by Django 5.2.7 on 2025-11-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_consumable_model_alter_consumable_modification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasteners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('min_quantity', models.PositiveIntegerField(verbose_name='Минимальный остаток')),
                ('link', models.URLField(verbose_name='Ссылка на закуп')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fasteners/', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Крепёж',
                'verbose_name_plural': 'Крепежи',
            },
        ),
        migrations.AlterModelOptions(
            name='consumable',
            options={'verbose_name': 'Запчасть для ремонта', 'verbose_name_plural': 'Запчасти для ремонта'},
        ),
    ]
