# Generated by Django 5.2.7 on 2025-11-21 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_fasteners_alter_consumable_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_made_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал'),
        ),
        migrations.AlterField(
            model_name='request',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_handled_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.CreateModel(
            name='IssueFasteners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдан')),
                ('fastener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastener_issues_created', to='inventory.fasteners', verbose_name='Расходник')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastener_issues_made_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastener_issues_bag', to=settings.AUTH_USER_MODEL, verbose_name='Получил')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдачи',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestFastener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('issued', 'Выдано')], default='pending', max_length=20)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fasteners', verbose_name='Расходник')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastener_requests_handled_by_user', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastener_requests_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
            options={
                'verbose_name': 'Оборудовние',
                'verbose_name_plural': 'Запросы на выдачу',
            },
        ),
    ]
