# Generated by Django 5.2.7 on 2025-11-21 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_issue_issued_by_alter_request_issued_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestfastener',
            name='consumable',
        ),
        migrations.AddField(
            model_name='requestfastener',
            name='fastener',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.fasteners', verbose_name='Крепёж'),
            preserve_default=False,
        ),
    ]
