# Generated by Django 5.2.7 on 2025-11-24 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_requestfastener_consumable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestfastener',
            name='fastener',
        ),
        migrations.RemoveField(
            model_name='requestfastener',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='requestfastener',
            name='requested_by',
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оборудовние', 'verbose_name_plural': 'Запросы на выдачу'},
        ),
        migrations.AddField(
            model_name='issue',
            name='fastener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.fasteners'),
        ),
        migrations.AddField(
            model_name='request',
            name='fastener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.fasteners', verbose_name='Крепёж'),
        ),
        migrations.AlterField(
            model_name='fasteners',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable', verbose_name='Платы'),
        ),
        migrations.AlterField(
            model_name='request',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable', verbose_name='Платы'),
        ),
        migrations.AlterField(
            model_name='request',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.DeleteModel(
            name='IssueFasteners',
        ),
        migrations.DeleteModel(
            name='RequestFastener',
        ),
    ]
