# Generated by Django 5.2.7 on 2025-12-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_requestfastener_fastener_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='manufacturing/', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Изготовление',
                'verbose_name_plural': 'Изготовление',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ['name'], 'verbose_name': 'Запчасть для ремонта', 'verbose_name_plural': 'Запчасти для ремонта'},
        ),
        migrations.AlterModelOptions(
            name='fasteners',
            options={'ordering': ['name'], 'verbose_name': 'Крепёж', 'verbose_name_plural': 'Крепежи'},
        ),
    ]
